services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: romain
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Utilisez une variable d'environnement pour le mot de passe
      POSTGRES_DB: databasestudymove
    ports:
      - '5432:5432'
    networks:
      - studymovenetwork

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: romain
      DB_PASSWORD: ${DB_PASSWORD} # Utilisez une variable d'environnement pour le mot de passe
      DB_NAME: databasestudymove
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025

    ports:
      - '8080:8080'
    depends_on:
      - db
      - mailhog

    networks:
      - studymovenetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Utilisez une variable d'environnement pour l'email
      PGADMIN_DEFAULT_PASSWORD: admin # Utilisez une variable d'environnement pour le mot de passe
    ports:
      - '5050:80'
    networks:
      - studymovenetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - studymovenetwork

  smtp:
    build:
      context: ./SMTP # Chemin vers votre Dockerfile Postfix
    ports:
      - '25:25' # Port SMTP
    environment:
      - mailname=yourdomain.com # Remplacez par votre domaine
      - smtp_user=user:password # Remplacez par vos informations utilisateur
    networks:
      - studymovenetwork

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - studymovenetwork
  swagger:
    build:
      context: ./ApiDocumentation
    ports:
      - '8081:80'
    networks:
      - studymovenetwork

networks:
  studymovenetwork:
    driver: bridge
